spring:
  application:
    name: framework
  datasource:
    url: jdbc:log4jdbc:mariadb://localhost:3306/biz?characterEncoding=UTF-8&serverTimezone=UTC
#    url: jdbc:log4jdbc:mariadb://222.117.122.75:3306/biz?characterEncoding=UTF-8&serverTimezone=UTC
    username: biz
    password: 1234
#    driver-class-name: org.mariadb.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  devtools:
    restart:
      enabled: false

mybatis:
  mapper-locations: mapper/**/*.xml
  configuration:
      map-underscore-to-camel-case: true
  type-aliases-package: com.biz.framework.common.map

logging:
  level:
    web: OFF
    jdbc.sqlonly: OFF
    jdbc.sqltiming: DEBUG
    jdbc.audit: OFF
    jdbc.resultset: OFF
    jdbc.resultsettable: OFF
    jdbc.connection : OFF
    org.hibernate.SQL: OFF
    org.springframework.web: OFF
    org.springframework.boot.autoconfigure: INFO
    com.zaxxer.hikari.HikariDataSource: ERROR
    org.springframework.jdbc.core.JdbcTemplate: OFF
  config: classpath:log4j2_dev.xml

popbill:
  #링크아이디
  linkId: PENTMIDEA
  #비밀키
  secretKey: ZjJZns6amTipvjraDMeiEBwTXdPBvAyAcIyFbzxjWRQ=
  #연동환경 설정, true-테스트, false-운영(Production), (기본값:false)
  isTest: true
  #인증토큰 IP 검증 설정, true-사용, false-미사용, (기본값:true)
  isIpRestrictOnOff: false
  #통신 IP 고정, true-사용, false-미사용, (기본값:false)
  useStaticIp: false
  #로컬시스템 시간 사용여부, true-사용, false-미사용, (기본값:true)
  useLocalTimeYn: true

biz:
  file:
    storage:
      allowed-extensions: hwp, doc, docx, ppt, pptx, xls, xlsx, jpg, jpeg, gif, png, txt, zip, pdf, egg, tif, tiff, bmp
  file-size: 10485760