spring:
  application:
    name: framework
  datasource:
#    url: jdbc:mariadb://localhost:3306/biz?characterEncoding=UTF-8&serverTimezone=UTC
    url: jdbc:log4jdbc:mariadb://localhost:3306/biz?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1879
#    driver-class-name: org.mariadb.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

mybatis:
  mapper-locations: mapper/**/*.xml
  configuration:
      map-underscore-to-camel-case: true
  type-aliases-package: com.biz.framework.common.dto

logging:
  level:
    web: OFF
    jdbc.sqlonly: OFF
    jdbc.sqltiming: DEBUG
    jdbc.audit: OFF
    jdbc.resultset: OFF
    jdbc.resultsettable: OFF
    jdbc.connection : OFF
    org.hibernate.SQL: OFF
    org.springframework.web: OFF
    org.springframework.boot.autoconfigure: INFO
    com.zaxxer.hikari.HikariDataSource: ERROR
    org.springframework.jdbc.core.JdbcTemplate: OFF
#  config: classpath:log4j2.xml